#!/bin/sh

# %W%
#
# XXX - does not check for checked out files.

make -s clean
VERS=`egrep 'MAJOR|MINOR' src/version.h | awk '{print $3}'` 
set `echo $VERS`
if [ $2 -lt 0 ] 
then	VERS=`echo $1$2 | sed s/-/alpha/`
else	VERS=`echo $VERS |sed 's/ /./'`
fi
D=lmbench-$VERS
git clone . $D
/bin/rm -rf $D/.git
tar czvf $D.tgz $D
/bin/rm -rf $D
make -s clean
