#!/bin/sh

if [ "X$OS" != "X" ] && echo "$OS" | grep -q '`'
then
    OS=
fi

if [ "X$OS" = "X" ]
then	OS=bloat-os
    MACHINE=`uname -m | sed -e 's/ //g' | sed -e 's?/?-?g'`
    SYSTEM=`uname -s | sed -e 's/ //g' | sed -e 's?/?-?g'`
    OS="${MACHINE}-${SYSTEM}"
    if [ -f ../scripts/gnu-os ]
    then
	NEW_OS=`../scripts/gnu-os 2>/dev/null | sed s/unknown-//`
	[ -n "$NEW_OS" ] && OS="$NEW_OS"
    fi
    if [ -f ../../scripts/gnu-os ]
    then
	NEW_OS=`../../scripts/gnu-os 2>/dev/null | sed s/unknown-//`
	[ -n "$NEW_OS" ] && OS="$NEW_OS"
    fi
fi
echo $OS
